### ISSUE TITLE
Markdown editor

### ISSUE THREAD

**Issue by wktdev** [borntofrappe/svelte-tutorial#26]
Hello, I found your markdown editor online via a search for "svelte markdown editor". I wanted to use it albeit I get a ton of rollup errors etc. Is there a version with instructions on how to incorporate it into a prexisting project? Thanks

**Comment by borntofrappe** [comment]
I wasn't able to address your issue in time, and given the lapse in time I prefer to close the issue. Let me know if you are still interested in the demo and I'll revisit it with the most recent Svelte version.
